"""Add dashboards and chat history

Revision ID: 54e1c31e605e
Revises: 
Create Date: 2026-01-14 12:51:23.391083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e1c31e605e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('dashboard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata_json')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'dashboard_id')
    # ### end Alembic commands ###
